apiVersion: v1
kind: Pod
metadata:
  name: town
  labels: 
    app: bond
spec: 
  containers: 
  - name: rtr-pod
    image: localhost:5000/hom:latest
    ports: 
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: shing
spec: 
  type: NodePort
  selector:
    app: bond
  ports: 
  - protocol: TCP
    port: 8082
    targetPort: 80
    nodePort: 30400
