apiVersion: v1
kind: Pod
metadata:
  name: kal
  labels: 
    app: dash
spec: 
  containers: 
  - name: cont-x
    image: localhost:5000/bak:latest
    ports: 
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: chang
spec: 
  type: NodePort
  selector:
    app: dash
  ports: 
  - protocol: TCP
    port: 8083
    targetPort: 80
    nodePort: 30401
